TEMP: try __all__ for ssh
Signed-off-by: Jiri Jaburek <comps@nomail.dom>

diff --git a/.github/workflows/pages.yaml b/.github/workflows/pages.yaml
--- a/.github/workflows/pages.yaml
+++ b/.github/workflows/pages.yaml
@@ -25,72 +25,89 @@ jobs:
 
       - name: Post-process .md and __init__.py files
         run: |
-            set -e
+          set -e
 
-            # move any *.md from the repo root to atex/, so it gets processed
-            # by the code below under the python module root
-            cp -n *.md atex/.
+          # move any *.md from the repo root to atex/, so it gets processed
+          # by the code below under the python module root
+          cp -n *.md atex/.
 
-            # transform any .md files to .py ones, putting their content into
-            # a raw docstring
-            while IFS= read -r -d '' path; do
-                name=${path##*/}
-                parent=${path%/*}
-                py="$parent/${name%.md}.py"
-                if [[ -e $py ]]; then
-                    echo "error: '$py' already exists"
-                    exit 1
-                fi
-                echo "transforming '$parent/$name' -> '$py'"
-                {
-                    echo "r'''"
-                    # [SOME_FOO.md](SOME_FOO.md) --> [SOME_FOO](SOME_FOO)
-                    # .. and also [some foo](SOME_FOO.md) --> [some foo](SOME_FOO)
-                    # .. but not [see url](https://external/SOME_FOO.md)
-                    #
-                    # additionally, remove backticks in headers (pdoc parser bugs)
-                    sed -r \
-                        -e 's/\[(.+).md\]\(([^:\]+).md\)/[\1](\2)/g ; s/\[(.+)\]\(([^:\)]+).md\)/[\1](\2)/g' \
-                        -e '/^#/s/`//g' \
-                        < "$path"
-                    echo "'''"
-                } > "$py"
-            done < <(find atex -name '*.md' -print0)
+          # transform any .md files to .py ones, putting their content into
+          # a raw docstring
+          while IFS= read -r -d '' path; do
+            name=${path##*/}
+            parent=${path%/*}
+            py="$parent/${name%.md}.py"
+            if [[ -e $py ]]; then
+              echo "error: '$py' already exists"
+              exit 1
+            fi
+            echo "transforming '$parent/$name' -> '$py'"
+            {
+              echo "r'''"
+              # [SOME_FOO.md](SOME_FOO.md) --> [SOME_FOO](SOME_FOO)
+              # .. and also [some foo](SOME_FOO.md) --> [some foo](SOME_FOO)
+              # .. but not [see url](https://external/SOME_FOO.md)
+              #
+              # additionally, remove backticks in headers (pdoc parser bugs)
+              sed -r \
+                -e 's/\[(.+).md\]\(([^:\]+).md\)/[\1](\2)/g ; s/\[(.+)\]\(([^:\)]+).md\)/[\1](\2)/g' \
+                -e '/^#/s/`//g' \
+                < "$path"
+              echo "'''"
+            } > "$py"
+          done < <(find atex -name '*.md' -print0)
 
-            # for every __init__.py, look for README.md in the same directory
-            # and if it exists, include it as a docstring inside __init__.py
-            # if it itself doesn't have one
-            while IFS= read -r -d '' path; do
-                if grep -E -q "^r?(\"\"\"|''')" "$path"; then
-                    echo "skipping '$path', has a docstring already"
-                    continue
-                fi
+          # for every __init__.py, look for README.md in the same directory
+          # and if it exists, include it as a docstring inside __init__.py
+          # if it itself doesn't have one
+          while IFS= read -r -d '' path; do
+            if grep -E -q "^r?(\"\"\"|''')" "$path"; then
+              echo "skipping '$path', has a docstring already"
+              continue
+            fi
 
-                parent=${path%/*}
-                readme="$parent/README.py"
-                [[ -e $readme ]] || continue
+            parent=${path%/*}
+            readme="$parent/README.py"
+            [[ -e $readme ]] || continue
 
-                # post-process the README docstring, add module-name/ to all relative
-                # Markdown links (pdoc treats __init__.py as if it was in the parent)
-                module_name=${parent##*/}
-                contents=$(sed -r "s/\[(.+)\]\(([^:\]+)\)/[\1](${module_name}\/\2)/g" < "$readme")
+            # post-process the README docstring, add module-name/ to all relative
+            # Markdown links (pdoc treats __init__.py as if it was in the parent)
+            module_name=${parent##*/}
+            contents=$(sed -r "s/\[(.+)\]\(([^:\]+)\)/[\1](${module_name}\/\2)/g" < "$readme")
 
-                # prepend the README to __init__.py
-                echo "prepending '$readme' to '$path'"
-                {
-                    printf '%s\n' "$contents"
-                    cat "$path"
-                } > "$path.new"
-                mv -f "$path.new" "$path"
-            done < <(find atex -name '__init__.py' -print0)
+            # prepend the README to __init__.py
+            echo "prepending '$readme' to '$path'"
+            {
+              printf '%s\n' "$contents"
+              cat "$path"
+            } > "$path.new"
+            mv -f "$path.new" "$path"
+          done < <(find atex -name '__init__.py' -print0)
 
       # also install '.' to get all dependencies from pip
       - name: Install pdoc
         run: python3 -m pip install pdoc .
 
+      - name: Prepare pdoc templates
+        run: |
+          mkdir -p pdoc_templates
+          cat > pdoc_templates/module.html.jinja2 <<'EOF'
+          {% extends "default/module.html.jinja2" %}
+
+          {% block style %}
+          {{ super() }}
+          <style>
+              /* Hide all class and module variables that do not have a docstring */
+              .variable:not(:has(.docstring)) {
+                  display: none !important;
+              }
+          </style>
+          {% endblock %}
+          EOF
+
       # generate HTML pages inside docs/
       - name: Generate docs
-        run: pdoc -n -d markdown -o docs ./atex !atex.cli
+        run: pdoc -n -d markdown -t pdoc_templates -o docs ./atex !atex.cli
 
       - uses: actions/upload-pages-artifact@v4
         with:
